Small syntax error change, die if --with-efence used, but efence not found

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -227,13 +227,13 @@ int main (int argc, char **argv)
 
 	cd = iconv_open ("UTF-8", "CP1252");
 	if (!cd)
-		exit (1);
+		exit 1
 	if (iconv (cd, &pc, &pc_len, &trans, &utf8_len) == -1 || pc_len != 0)
-		exit (1);
+		exit 1
 	if (memcmp (utf8, transbuf, utf8_real_len) != 0)
-		exit (1);
+		exit 1
 
-	exit (0);
+	exit 0
 }], AC_MSG_RESULT(yes); have_iconv=yes, [AC_MSG_RESULT(no);], AC_MSG_RESULT(not cross compiling);)])])
 
 dnl ##  Fixed AC_TRY_RUN warning, missing third argument. -DD 22/01/2002
@@ -666,7 +666,11 @@ if test "x$with_efence" != "xno"; then
 		LIBS="$LIBS -lefence"
 	else
 		use_efence=false
-	        AC_MSG_WARN([Unable to locate ElectricFence library!])
+		echo "Unable to locate ElectricFence malloc() debugging library!"
+		echo "Please download from ftp://ftp.perens.com/pub/ElectricFence/"
+		echo "You may also try omitting --with-efence when running configure."
+		echo ""
+		exit 1
 	fi])
 fi
 
