Jun 29, 1997    Kenneth Albanowski 0.7.2
        Complete reimplemenation of library production, using version 0.9h of
                Gordon Matzigkeit's libtool package.
        Added Tcl, Tk, & Python auto-detection to configure script (use
                'configure --help' to see what options can be modified.)
        Rewrote Python compilation to use standard dynamic compilation technique.
        Rewrote Tcl compilation to use libtool and to generate binaries.
        Added David Warren's patch to add serial delays for SGI.

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -6,14 +6,18 @@ dnl Process this file with autoconf to produce a configure script.
 AC_INIT(include/pi-cmp.h)
 AC_CONFIG_AUX_DIR(scripts)
 
+
 dnl Check host type
 AC_CANONICAL_HOST
+
 
 dnl Checks for programs.
 AC_PROG_CC
 AC_PROG_INSTALL
+AM_PROG_LIBTOOL
 AC_PROG_RANLIB
 AC_PROG_YACC
+
 
 AC_CHECK_PROGS(CXX, $CCC c++ g++ gcc CC cxx cc++, gcc)
 
@@ -58,8 +62,8 @@ EXT=''
 CXXLIBS=''
 if test $ac_cv_prog_cxx_works = yes; then
   ccexecs='$(CCEXECS)'
-  cclib='libpicc.a'
-  libcclib='libcc/libpicc.a'
+  cclib='libpicc.la'
+  libcclib='libcc/libpicc.la'
   SUBMAKE_COMM_CC='cd libcc ; $(MAKE) '
 fi
 AC_SUBST(ccexecs)
@@ -122,6 +126,155 @@ if test $ac_cv_termios_cspeed = yes; then
   AC_DEFINE(TERMIOS_CSPEED)
 fi
 
+dnl Check packages
+AC_ARG_WITH(tcl,      [  --with-tcl=tclbasedir   use Tcl     [default=yes]])
+AC_ARG_WITH(tk,       [  --with-tk=tkbasedir     use Tk      [default=yes]])
+AC_ARG_WITH(python,   [  --with-python=pylibbase use Python  [default=yes]])
+#AC_ARG_WITH(readline, [  --with-readline         use Readline 2.0])
+
+if test "x$with_tcl" = "xyes" || test "x$with_tcl" = "x" ; then
+	for tcl_path in /usr /usr/local /usr/local/tcl7.5 /usr/local/tcl7.6 /usr/local/tcl8.0; do
+		if test -f $tcl_path/lib/tclConfig.sh ; then
+			with_tcl=$tcl_path; break
+		fi
+	done
+	if test "x$with_tcl" = "xyes"; then
+		echo "Unable to find Tcl base installation directory."
+		echo "Please give directory (such as /usr/local) as argument to --with-tcl=dir."
+		with_tcl=no
+	fi
+fi 
+
+AC_MSG_CHECKING(for Tcl)
+TCL_VERSION=""
+TCL_LIBS=""
+TCL_LIB_SPEC=""
+TCL_PACKAGE_SPEC=""
+TCL_INC=""
+TCL_BIN=""
+TK_VERSION=""
+TK_LIBS=""
+TK_LIB_SPEC=""
+TK_INC=""
+TK_BIN=""
+if test "x$with_tcl" = "x"; then
+	AC_MSG_RESULT(not found)
+elif test "x$with_tcl" = "xno"; then
+	AC_MSG_RESULT(not used)
+else
+	if ! test -f $with_tcl/lib/tclConfig.sh; then
+		AC_MSG_RESULT(Unable to find $with_tcl/tclConfig.sh)
+	else
+		. $with_tcl/lib/tclConfig.sh
+		AC_MSG_RESULT(version $TCL_VERSION from $with_tcl)
+		TCL_INC="-I$TCL_PREFIX/include"
+		TCL_BIN="$TCL_EXEC_PREFIX/bin"
+		CFLAGS="$CFLAGS -DTCL \$(TCL_INC)"
+		CXXFLAGS="$CXXFLAGS -DTCL \$(TCL_INC)"
+		TCLTK_LIBS="$TCL_LIB_SPEC $TCL_LIBS"
+	
+		if test "x$with_tk" = "xyes" || test "x$with_tk" = "x"; then
+			for tk_path in $with_tcl; do
+				if test -f $tk_path/lib/tkConfig.sh ; then
+					with_tk=$tk_path; break
+				fi
+			done
+			if test "x$with_tk" = "xyes"; then
+				echo "Unable to find Tk base installation directory."
+				echo "Please give directory (such as /usr/local) as argument to --with-tk=dir."
+				with_tk=no
+			fi
+		fi 
+		
+		AC_MSG_CHECKING(for Tk)
+		if test "x$with_tk" = "x"; then
+			AC_MSG_RESULT(not found)
+		elif test "x$with_tk" = "xno"; then
+			AC_MSG_RESULT(not used)
+		else
+			if ! test -f $with_tk/lib/tkConfig.sh; then
+				AC_MSG_RESULT(Unable to find $with_tk/tkConfig.sh)
+			else
+				. $with_tk/lib/tkConfig.sh
+				AC_MSG_RESULT(version $TK_VERSION from $with_tk)
+				TK_INC="-I$TK_PREFIX/include"
+				TK_BIN="$TK_EXEC_PREFIX/bin"
+				CFLAGS="$CFLAGS -DTK \$(TK_INC)"
+				CXXFLAGS="$CXXFLAGS -DTK \$(TK_INC)"
+				TCLTK_LIBS="$TK_LIB_SPEC $TCL_LIB_SPEC $TK_LIBS"
+			fi
+		fi
+	fi
+fi
+
+AC_SUBST(TCL_VERSION)
+AC_SUBST(TCL_LIBS)
+AC_SUBST(TCL_LIB_SPEC)
+AC_SUBST(TCL_PACKAGE_PATH)
+AC_SUBST(TCL_INC)
+AC_SUBST(TCL_BIN)
+AC_SUBST(TK_VERSION)
+AC_SUBST(TK_LIBS)
+AC_SUBST(TK_LIB_SPEC)
+AC_SUBST(TK_INC)
+AC_SUBST(TK_BIN)
+AC_SUBST(TCLTK_LIBS)
+
+TCLEXECS=''
+if test ! "x$TCL_VERSION" = "x"; then
+	TCLEXECS='pilot-debug$(EXT)'
+fi
+AC_SUBST(TCLEXECS)
+
+
+if test "x$with_python" = "xyes" || test "x$with_python" = "x" ; then
+	for py_path in /usr /usr/local /usr/local/python1.3 /usr/local/python1.4 /usr/local/python1.5; do
+		for ver in 1.3 1.4 1.5; do
+			if test -f $py_path/lib/python$ver/config/Makefile ; then
+				with_python=$py_path; break
+			fi
+		done
+	done
+	if test "x$with_python" = "xyes"; then
+		echo "Unable to find Python base directory."
+		echo "Please give directory (such as /usr/local/) as argument to --with-python=dir."
+		with_python=no
+	fi
+fi 
+
+AC_MSG_CHECKING(for Python)
+
+PYTHONBASE=''
+PYTHONLIBDIR=''
+PYTHONINCDIR=''
+PYTHONVER=''
+if test "x$with_python" = "x"; then
+	AC_MSG_RESULT(not found)
+elif test "x$with_python" = "xno"; then
+	AC_MSG_RESULT(not used)
+else
+	for ver in 1.3 1.4 1.5; do
+		if test -f $with_python/lib/python$ver/config/Makefile ; then
+			PYTHONVER=$ver; break
+		fi
+	done
+	
+	if test ! -f $with_python/include/python$PYTHONVER/Python.h; then
+		AC_MSG_RESULT(Unable to find $with_python/include/python$PYTHONVER/Python.h)
+	elif test ! -f $with_python/lib/python$PYTHONVER/config/Makefile; then
+		AC_MSG_RESULT(Unable to find $with_python/config/Makefile)
+	else
+		AC_MSG_RESULT(Python version $PYTHONVER in $with_python)
+		PYTHONBASE=$with_python
+		PYTHONLIBDIR=$with_python/lib/python$PYTHONVER
+		PYTHONINCDIR=$with_python/include/python$PYTHONVER
+	fi
+fi
+AC_SUBST(PYTHONBASE)
+AC_SUBST(PYTHONLIBDIR)
+AC_SUBST(PYTHONINCDIR)
+AC_SUBST(PYTHONVER)
+
 dnl Derive warning flag
 AC_CACHE_CHECK([for maximum warnings compiler flag],
   ac_cv_cwflag,
@@ -134,8 +287,6 @@ AC_CACHE_CHECK([for maximum warnings compiler flag],
 esac])
 CWFLAG=$ac_cv_cwflag
 AC_SUBST(CWFLAG)
-
-CFLAGS="$CFLAGS `perl -e 'use Config; print $Config{cccdlflags}'`"
 
 dnl NeXT support
 case "$host" in
@@ -153,4 +304,9 @@ if test $ac_cv_prog_cxx_works = yes; then
   cc_m='libcc/Makefile'
 fi
 
-AC_OUTPUT(libsock/Makefile $cc_m Makefile)
+
+LTLIBOBJS=`echo "$LIBOBJS" | sed 's/\.o/\.lo/g'`
+AC_SUBST(LTLIBOBJS)
+LTALLOCA=`echo "$ALLOCA" | sed 's/\.o/\.lo/g'`
+AC_SUBST(LTALLOCA)
+AC_OUTPUT(libsock/Makefile $cc_m Makefile Python/Makefile Tcl/Makefile)
